### ISSUE TITLE
Evading Mutes through GTS

### ISSUE THREAD

**Issue by Xulrya** [EnvyWare/EnvyGTS#35]
When muted, players are still able to add named items and Pokemon to GTS to talk in the chat. They use this exploit to continue conversations during their mute and there's no way on our end for us to stop it.

**Comment by Mike5357** [comment]
Most plugins that offer a mute feature such as Essentials have a configurable blocked command list for when a player is muted. If yours doesnt, the only other workaround I can recommend is creating a muted rank using your permissions plugin and setting the GTS permission to false and applying it to the player. Otherwise, a fix for this isn't really in scope of the plugin itself.
